version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      network: host
      args:
        - UID=${UID}
        - GID=${GID}
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    tty: true
    depends_on:
      - db
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: aiit_g2
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_DB: reminder_dev
      RAILS_ENV: development
    user: "${UID}:${GID}"

  db:
    image: postgres:14.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reminder_dev
      POSTGRES_USER: aiit_g2
      TZ: "Asia/Tokyo"
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
