FROM ruby:3.1.3

ARG UID=1000
ARG GID=1000

ENV RAILS_ENV=development

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN apt update -y && apt -y install libpq-dev

RUN mkdir /myapp
WORKDIR /myapp
ADD Gemfile /myapp/Gemfile
ADD Gemfile.lock /myapp/Gemfile.lock
RUN bundle install
ADD . /myapp

RUN groupadd -g $GID group2 && \
    useradd -m -s /bin/bash -u $UID -g $GID group2
RUN chown -hR group2:group2 /myapp

USER group2
WORKDIR /myapp
