version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
      network: host
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    depends_on:
      - db
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: aiit_g2
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_DB: remainder_dev

  db:
    image: postgres:14.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: remainder_dev
      POSTGRES_USER: aiit_g2
