default: &default
  adapter: postgresql
  encoding: unicode
  host: "<%= ENV.fetch('POSTGRES_HOST', '127.0.0.1') %>"
  username: "<%= ENV.fetch('POSTGRES_USER', 'aiit_g2') %>"
  password: "<%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>"
  pool: 5

development:
  <<: *default
  database: "<%= ENV.fetch('POSTGRES_DB', 'remainder_dev') %>"

test:
  <<: *default
  database: remainder_test