name: Build
on:
  push:
    branches:
      - 'main'
      - 'add-deploy'

jobs:
  tests:
    uses: ./.github/workflows/unit-test.yml
    secrets:
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - run: >
          curl --location --request POST 
          'https://cloudbuild.googleapis.com/v1/projects/collaborative-g2/triggers/remainder:webhook?key=${{secrets.BUILD_API_KEY}}&secret=${{secrets.BUILD_SECRET}}' 
          --header 'Content-Type: application/json'