name: Unit Test
on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
          bundler: 2.3.26

      #      - uses: actions/setup-node@v3
      #        with:
      #          node-version: '12.22.5'
      #          cache: 'yarn'
      #
      #      - name: Yarn install
      #        run: yarn install --frozen-lockfile

      - name: Migrate database
        run: |
          echo $RAILS_MASTER_KEY
          bundle exec rails db:migrate

      - name: Run test
        run: bundle exec rails test
