name: Unit Test
on:
  workflow_call:
    secrets:
      rails_master_key:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.rails_master_key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true
          bundler: 2.3.26

      - name: Migrate database
        run: bundle exec rails db:migrate

      - name: Run test
        run: bundle exec rspec

      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
